channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.2
  - cloudpickle=1.5.0
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.33.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.1.1
  - numba=0.50.1
  - numexpr=2.7.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyface=7.0.1
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - spyder-kernels=1.9.3
  - sqlite=3.33.0
  - statsmodels=0.11.1
  - tbb=2020.2
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - traits=6.1.1
  - traitsui=7.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wurlitzer=2.0.1
  - xlrd=1.2.0
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - appdirs==1.4.4
    - apptools==4.5.0
    - configobj==5.0.6
    - dipy==1.1.1
    - doit==0.33.1
    - envisage==4.9.2
    - imageio-ffmpeg==0.4.2
    - iniconfig==1.1.1
    - mayavi==4.7.2.dev0
    - meshio==4.1.1
    - mne==0.21.1
    - mne-bids==0.6
    - mypy==0.790
    - mypy-extensions==0.4.3
    - neo==0.8.0
    - nibabel==3.1.1
    - nilearn==0.6.2
    - pluggy==0.13.1
    - py==1.10.0
    - pyinotify==0.9.6
    - pyqt5==5.15.0
    - pyqt5-sip==12.8.0
    - pysurfer==0.11.0
    - pytest==6.2.2
    - pytest-sugar==0.9.4
    - python-picard==0.4
    - pyvista==0.25.3
    - pyvistaqt==0.2.0
    - quantities==0.12.4
    - scooby==0.5.6
    - sklearn==0.0
    - termcolor==1.1.0
    - toml==0.10.2
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
    - vtk==9.0.1
