channels:
  - conda-forge
  - defaults
dependencies:
  - ipython>=7
  - matplotlib>=3
  - numba>=0.50
  - numpy>=1.19
  - pandas>=1.1.1
  - pip>=20
  - python=3.8
  - scipy>=1.5
  - tqdm>=4.48
  - xlrd>=1.2
  - pip:
    - doit==0.33.1
    - envisage==4.9.2
    - iniconfig==1.1.1
    - mayavi>=4.7.2
    - meshio==4.1.1
    - mne>=0.21.1
    - mne-bids==0.6
    - pysurfer==0.11.0
    - pytest==6.2.2
    - pytest-sugar==0.9.4
    - pyvista==0.25.3
    - sklearn==0.23
    - termcolor==1.1.0
    - vtk==9.0.1
